mybatis:
  type-aliases-package: com.meng.entity


#开发配置
spring:
  datasource:
    url: jdbc:mysql://107.173.149.218:3306/demo?useUnicode=true&characterEncoding=UTF-8

    username: demo
    password: Mb3LCaH6ZTzLHXfi
    driver-class-name: com.mysql.jdbc.Driver
